### ISSUE TITLE
MDM YAML read wrong wavelength?

### ISSUE THREAD

**Issue by pllim** [spacetelescope/specviz#146]
Gisella reported her emission line was unexpectedly blueshifted. Need to investigate.

**Comment by pllim** [comment]
@gderosa2004, if you have the exact file with an emission line and where it is supposed to be, that would  be great for debugging.

**Comment by pllim** [comment]
From my vague memory of the tag-up, the line shown at 4950 Angstrom should be [O III] that is supposed to be at 5007 Angstrom (rest wavelength). 

![screenshot](https://cloud.githubusercontent.com/assets/2090236/13324682/bcdd75c6-dbac-11e5-9e33-6c0ee5dff01f.png)

Here is the actual code in `core/data.py` (that I did not write, not sure who wrote it) that converts WCS to dispersion:
```python
self._dispersion = np.arange(self.data.size)
try:
    crval = self.wcs.wcs.crval[0]
    cdelt = self.wcs.wcs.cdelt[0]
    end = self.data.shape[0] * cdelt + crval
    self._dispersion = np.arange(crval, end, cdelt)
except:
    logging.warning(...)
```

When this code is run with the data, I get this `RuntimeWarning` in the terminal:
```python
.../specviz/core/data.py:86: RuntimeWarning: cdelt will be ignored since cd is present
  cdelt = self.wcs.wcs.cdelt[0]
```

So, something might be wrong with the formula. @stscieisenhamer? @ibusko?

**Comment by gderosa2004** [comment]
Sorry, I was in meetings all morning.
I’m attaching the txt version of the 120204 spectrum for comparison. This has the correct wavelength scale.

([OIII] brightest line is at 5007 rest frame)

G

**Comment by pllim** [comment]
Try again, @gderosa2004 . The wavelength after fix is about 5090 Angstrom, which seems to make more sense to me. By the way, I can't easily parse your text above on Linux Emacs. But the issue should be fixed in the latest master. Let me know if it still looks weird.

![screenshot](https://cloud.githubusercontent.com/assets/2090236/13327091/7c06f98c-dbb6-11e5-9f90-f1f6a9878f6e.png)

**Comment by gderosa2004** [comment]
Hi Pey-Lian,

Have you pushed the update? It looks like I am up to date and the issue is not fixed yet.
Maybe I’m in the wrong branch..

G

**Comment by pllim** [comment]
I just did it a few minutes ago. Pushed to master. To be sure, do this:
```
$ git pull
$ git clean -xdf
$ python setup.py install
```

**Comment by pllim** [comment]
I used the test data you provided to the sprint.

**Comment by gderosa2004** [comment]
Still have the same issue (see plot attached). I followed all of your suggestions.

Also, how do I overplot 2 spectra?

G

**Comment by nmearl** [comment]
Re: who wrote the code: @pllim. The original code in this project was written by me, so general you can blame me for lazy assumptions. :stuck_out_tongue_closed_eyes:

@gderosa2004 Do you mean two spectra from two data sets that you loaded in? Or plotting two layers from a single data set?

**Comment by gderosa2004** [comment]
2 spectra from 2 different data sets

**Comment by gderosa2004** [comment]
@pllim I still have the same issue with exactly the same spectrum you're using
![screen shot 2016-02-25 at 2 17 31 pm](https://cloud.githubusercontent.com/assets/15363065/13331253/a12b970e-dbca-11e5-93bd-9d902ba3009f.png)

**Comment by pllim** [comment]
Turns out Gisella was using wrong repo. It is resolved.
