### ISSUE TITLE
Models on slice have incorrect dispersion

### ISSUE THREAD

**Issue by nmearl** [spacetelescope/specviz#180]
After creating a layer slice, if a user than creates a model using that slice, the mask is incorrectly applied and the model seems to shift to the beginning of the source data.

**Comment by pllim** [comment]
I think I fixed that this morning. Are you using the latest dev?

**Comment by pllim** [comment]
See #175 to be specific.

**Comment by nmearl** [comment]
I just pulled the latest, and it seems that it crashes now.

1. Open a data file (generic_spectra.fits)
2. Put down an ROI
3. Create a layer slice (left-most button below the layer dock)
4. Add a model
5. Create model layer (the model extends outside the bounds of the layer slice)
6. Add another model
7. Update model layer
8. Crashes

Also, that the model layer extends outside the layer slice region is a different behavior than when do *not* create a layer slice first. That is:

1. Open a data file (generic_spectra.fits)
2. Put down an ROI
3. Add a model
4. Create model layer

In this latter case, the model layer is restrained to the selected region.

**Comment by pllim** [comment]
The first workflow -- Yes, I can reproduce the crash. I added a shape check in my PR because it does not make sense to apply a mask that is smaller than the actual data (always has been that way but I don't know why you nor Ivo encountered it sooner). I guess the problem here is that I fixed my use case but did not fix the real underlying problem, that is model fitting is not handling mask properly from layer to layer. Short of refactoring how layers pass masks around, I don't know another solution. Any ideas?

The second workflow -- Yes, I noticed that as well, even before my PR today. Is that not supposed to happen? I think @ibusko also previously reported the same thing.

**Comment by nmearl** [comment]
> The second workflow -- Yes, I noticed that as well, even before my PR today. Is that not supposed to happen? I think @ibusko also previously reported the same thing.

No, it's not the intended behavior. But this all should be fixed with 64ab4de2d2878eaa216d6b7a2fe84e89cba846dd.

**Comment by pllim** [comment]
@nmearl , with the second workflow, I still see model being restrained to ROI with latest dev. When I delete the ROI, select the original layer, and select the model layer again, I get this:

```python
ERROR:root:Traceback (most recent call last):
  File ".../specviz/core/comms.py", line 112, in wrapper
    return func(*args, **kwargs)
  File ".../specviz/ui/controller.py", line 589, in update_statistics
    values = current_layer.data[mask[current_layer._mask]]
IndexError: index 11145 is out of bounds for axis 1 with size 8551
```

**Comment by nmearl** [comment]
This should be fixed with the latest version.
